### ISSUE TITLE
KPA Key body recovery is possible!

### ISSUE THREAD

**Issue by ed770878** [ikizir/HohhaDynamicXOR#15]
**It is possible to recover the key body** in a known plain text attack, as a constraint satisfaction problem.  I wrote a program that, with 1000 known plain and cipher text pairs, can recover a key body in about a minute, [here in my fork](/ed770878/HohhaDynamicXOR).

Since you force pushed your branch and broke the merge, I guess you wouldn't be willing accept a pull request from me.  I know you're just going to close this, too, and probably throw some insults my way, but whatever.  It's your loss really, not to engage in the discussion and analysis of your algorithm.  I guessed that the key could be solved as a csp in the discussion of my second pull request to you, if you recall since you went ahead and deleted all the comments.

**Comment by ikizir** [comment]
1. I don't delete useful work and respectful technical conversations.
2. You didn't tell something new and, I have been believing and I still am beleiving that you're trying to mislead the people with "partially true" information here.  @And I am explaining why:

I wrote this on the first versions of the wiki :https://github.com/ikizir/HohhaDynamicXOR/wiki/Reliability 

 "... So far, we detected a "unique" vulnerability, which can be "theoretically" defended by the "Crypto Experts": Intercepting both the plaintext AND the salt(nonce). But we consider it only "theoretical" because, key's original salt value is only used to encrypt&decrypt salt values to be transmitted with each ciphertext. Salt values are random by nature. If someone claims this "theoretical possibility", he must also explain us "how" he can intercept the nonce value! But anyway, a "theoretical possibility" is still a threat and you must consider this possibility in your real life applications."

And your algorithm is that proof:

You suppose you "already have" those variables in order to "reveal" the key body(A beloved friend of God is giving you all this information right?)

You need 32 bits CRC value
You need 1000 plaintexts AND 64 bits salt(nonce) values   

Roughly; the algorithmic complexity of your "key body reveal" is 2^(64+11+6) \* Complexity Of your algorithm) = 2^81 \* Complexity of your algorithm! (Which is I think, close to half of the number of atoms in the  @universe)! And surprise: I made you a favor and I didn't add the complexity of the "plaintexts" you "just intercepted"! (If I add, the number will be toooo high. I like challenge)

At least 2^81. And you tell that you worked only with 2-Jumps keys! We don't know the complexity for greater number of  @jumps.  

You must have a really complex computer to make those calculations in a "few minutes"! But Oh! I forgot to mention: You have a running code :) It makes something with "pre-given divine information" :) Let me name your program. Please, please:  Let's call it  "God's machine", which, functions with mysterious ways with "Divine information" :)

Even me, even me, I believed what you wrote when I read your comment here. Then I directly looked at your code. Then I read your instructions: "Your program is supposed to know nearly every secret information in order to work". And there is not any simple explanation for us, mortals, how you have obtained this information.  :) 

I am never insulting to you or someone else, unless, they try to insult me after having proved that their intention is not a technical conversation but to mislead the people with "partially true" information.

So far, you are "sane". And your work helps me and the community to think about the "theoretical weaknesses" of the algorithm.  And I appreciate it.

As far as you and your comments are sane, they remain here as a useful source of information. I keep it here because it's a typical example of "misleading with partially true" disinformation. 

I've just read the comments about me and Schneier laws :)

You seem to be a typical disciple of him. I even suspect you're Schenier himself :)

Schneier is one of the recent prophets of  "if I already have ..." religion :)

"If" he has the right tools he can do anything. And I  truly believe him. He can do it "if he already has" :)

You are following your prophet: We all know that you can move the earth "if you have the proper tool". But you never explain to us, mortals, "small details", as, how you will build that tool. 

Here are some of the capabilities of your prophet:
https://www.schneierfacts.com/

**Comment by ed770878** [comment]
> I even suspect you're Schenier himself :)

It would be an honor, but I am not worthy.  It's not that people follow him blindly, rather that he has gained respect for doing useful work.  Its like if you go to a university, the professors are not God, and learning from them is not practicing religion.

> At least 2^81. And you tell that you worked only with 2-Jumps keys! We don't know the complexity for greater number of jumps.

It works for greater than two jumps, and keys larger than 128.  This is a general attack against any number of jumps, any length of key.  Just add enough known plain texts and even the more difficult keys can be recovered in a reasonable amount of time.  I also assume that I can get the key length and jumps using the other attacks, but if not it's no big deal.  There are only 256 (one byte) possible number of jumps (including zero and one jump - so really there are only 254).  Key length must be a power of two less or equal to 64k (two bytes), so there are only 16 possible lengths (including zero through 64 - so really there are only 10 possible lengths).  I can just run the same attack `254 * 10 = 2540` times if I don't already know the jumps and key length.  That's a small number.

You claim that the complexity of brute forcing it is something like 2^81.  That would be true if every single possible key were tried.  But if we can backtrack the search early, say after a few bytes we can rule out any key with that combination of a few bytes, then we don't have to search any more keys with that combination.  We can reduce the search space to something more reasonable, that can be seared in minutes not the age of the universe.  That's what the algorithm does, backtracking search.

I don't need to guess the whole crc of the key either.  I guess I didn't explain this detail in the attack.  I only need to guess one byte of the crc at the start of the search, and then only one bit at a time for the remainder of the search.  When the search finds a solution, the guessed crc can be compared to the actual computed crc to validate a solution.  In your algorithm you could even make the initial value of `V` something secret, not even related to the crc of the key, and the attack would still work.

> You must have a really complex computer to make those calculations in a "few minutes"!

No, I have just a plain old Intel processor on an inexpensive laptop.  You are of course free to try it for yourself, on your more worthy machine.

> And there is not any simple explanation for us, immortals how you have obtained this information. :)

I assume you mean, how do I know 1000 plain and cipher texts?  First of all, you are making a pretty lame excuse for security with that line of argumentation.  Even if I know that information, a secure algorithm should not so easily be broken by a known plain text attack.  But anyway, let's consider a situation in which I might have 1000 known plain and cipher texts.

You have heard of [ransomware](https://en.wikipedia.org/wiki/Ransomware), right?  Imagine your encryption algorithm is used in some ransomware, to encrypt all the files on my computer.  I'm sure you would just love to do that right about now?  Suppose my most recent backup is a month old, and I would lose a bunch of work from this month if I just revert to the backup.  I have at least 1000 files in the backup that I haven't touched in a month, and the same files are encrypted on my computer.  I can use that information, the known plain text files in the backup, and the cipher texts on my computer, to recover the key.  With the key, I can recover the rest of my files that were not backed up.

**Comment by ikizir** [comment]
Still you don't mention about "how you know nonce values"
Without those nonce values, your "plaintexts" are useless, since, there  are padding bytes. You insist to consider the algorithm as a stream cipher but in fact, with padding, it more like a block cipher. 
You are just exthausting me.
I have no time to play with you.
The "real", "mathematical" and concrete algorithm complexity for your algorithm is not 2^81
It is 2^81 \* (256^PlainTextLength) ---> This is mathematic, not abstract "If I already know ..." kind of phantasms(even more since, PlainText is rounded up to PacketSize)
Go play with Schneier and his band in your fictif world.
If there is anyone who reads all these and believes that what you tell is a real threat after all I wrote, I suggest them to not to use this algorithm.

I am certain that this algorithm fits "perfectly" for my specific needs. I know how to use.
I also opened it to public with MIT&GPL.
I wrote in wiki what are "theoretical threats" long before some wannabees tried to show me some extreme examples from a fictional world.  
I have a software to develop.
Again, go play with Schneier. He has a lot of time for these kind of discussions, not me. You can discuss together about your "God's Machine" working with "divine intelligence".  
If you try to write more and getting delicate, as you did last time, I will remove your comments again. Don't do that please. You told what you wanted to tell, I told what I wanted to tell. Comments will stay here. 
It's enough.

**Comment by ed770878** [comment]
> https://www.schneierfacts.com/

That's funny.  Thanks for the link!

**Comment by ikizir** [comment]
You're wellcome :)

And in order to better understand that Hohha Encryption Ecosystem is resistant to known plaintext attacks, produce 1000 encrypted Hohha packets: You know both the plaintexts and ciphertexts. (But not the salt(nonce) values!".
Try try to modify your algorithm to run "without assuming that you already know nonce values".
You will see that they are resistant to known plaintext attacks.

**Comment by ed770878** [comment]
I'm going to take a break from this project for a little while, but I'll be back.  Working on the code is fine, and there is still more that I plan to do, but later.

There are two things on my todo list, in the following order:

1. The current version of the KPA key recovery attack has a run time in the range of a few seconds to just under an hour, depending on input.  I think I can do better, using iterative deepening and a value-ordering heuristic.  My goal is to improve the current attack run time to under a second, and also be able to recover larger keys with more jumps in a reasonable amount of time, like under an hour.

2. After a cursory review of the packet format, *I believe that it is vulnerable to a ciphertext only attack*.  I have a specific design for an attack in mind.  I believe that it will be able to recover the key body, the key crc, and the original key salt, given nothing more than encrypted packet headers.  To be clear, what I am saying is that I believe the algorithm is *less secure* with the packet header than it is without the packet header.  If COA is possible, then the only way to protect the message will be to make it impossible to intercept the cipher text - but if it's impossible to intercept, why encrypt?

Both of these todo items will take a few hours of dedicated programming, each.  I have specific changes planned for the code, just not the motivation to continue with this project for now.  To be honest, working on the code is fine, but your rejection of "theoretical" vulnerabilities, and most of all your harassing comments, really drain my energy to continue working on this.  On that note, there are two ways we might be able to proceed.

1. If we can't have a conversation about it, then let's just leave it at this for now.  When I'm ready, I'll return, I'll try to code up the attack, and if it works, I'll let you know.

2. If you're ready to be a grown up about it, then we can talk about the theoretical attacks.  You can engage in the discussion, take the time to learn the attacks and how they work, so you can really understand exactly why your algorithm is vulnerable.  Two things I won't allow are harassment, and changing the algorithm to do something else.  If you still don't accept that the attacks are possible, and I eventually have to write code to prove the attack, I don't want you to waste my time by changing the algorithm.  If you believe the algorithm is not vulnerable to attack, then there is no need to change it, right?  Therefore, if you change the algorithm, I would consider it to be your acknowledgement that yes, the algorithm is vulnerable.

If you would like to talk about theoretical attacks, show me.  Please describe in your own words how the current "theoretical" attacks work.  It's completely acceptable to say "but it only works if...", and the doesn't work if any of the assumptions are not true.  What I want to see is your willingness to consider a situation where those assumptions are true, even if the assumptions seem unreasonable, and then explain why the attack is possible and how it works.

Just so you know, the kind of reasoning I am talking about isn't "Schneier's law", practiced by his disciples or anything like that.  Schneier's law might be relevant, but it's something completely different and maybe too far over your head for you to understand - don't worry you'll work your way up eventually.  The kind of reasoning that I am talking about is propositional logic, practiced in all fields of math and science.  If you start with some assumptions, no matter how absurd those assumptions may be, by implication it can be proved that something else must be true if the assumptions are true.  Blame [Chrysippus](https://en.wikipedia.org/wiki/Chrysippus), not Schneier.
