### ISSUE TITLE
Understand decryption

### ISSUE THREAD

**Issue by nils-werner** [ikizir/HohhaDynamicXOR#4]
As I understand from your explanations during encryption you do
1. Encrypt next plaintext byte using key
2. Mangle key using last used plaintext byte
3. Goto 1

That way you say you have "encrypted the key using the plaintext and the plaintext using the key".

Now I imagine to decrypt the data you need to
1. Decrypt next coded byte using key
2. Mangle key using plaintext byte you just calculated
3. Goto 1

Is that correct?

What exactly is the benefit then when your message is intercepted as opposed to AES? In both cases the intercepting party only needs the key to successfully calculate the inverse encryption.

And, assuming your algorithm has no weaknesses, no known shortcut exists; all possible key combinations must be guessed, no matter if using AES or Hohha.

**Comment by ikizir** [comment]
Assuming you intercepted a communication somehow.
You know the plaintext and the ciphertext.
It is impossible to find out what the key is.
Because, there are additional 2^72 possibilities.
On each transmissions, we send 8 bytes secret random salt(or nonce) data to receiver + 8 byte key crc.
This random data is used for every byte to be encrypted. The starting jump point and all the path depends on that value. And when those values are different, the key produces entirely different ciphertexts.
Intercepting communication and knowing ciphertext/plaintext pairs is not meaningful unless it you intercept a very very high number of cipertext/plaintext pairs. And my mathematical backgound is not enough to tell you that "high number".

**Comment by Fbonazzi** [comment]
I second what Werner says.

If I intercept a communication (meaning I intercept the IV and ciphertext), the only information that I need to know to decrypt the ciphertext is, indeed, the key. So all this complex number mangling you spent so much time devising and "explaining" goes right out of the window - and expectedly so.
Then the problem is reduced to figuring out the key, which may at worst be as hard as bruteforcing the key.

So your algorithm already does not provide anything more than, say, AES, without even delving into the inevitable problems that your algorithm and implementation (since you do not provide an algorithm specification) will have.

**Comment by ikizir** [comment]
AES uses last encrypted data to produce encrypted text
Hohha is not directly using last enrypted data to produce ciphertext
But it uses indirectly by using it updating "key" itself
This property,  makes Hohha much more stronger than AES.  
AES has a static key and makes "rounds"
Hohha updates the key itself, with every encrypted byte. 
When we XOR the value at key position 7 for example, with a plaintext; byte.
The key at position 7 has not the same value anymore. This makes Hohha much more harder to break.
I hope, I could answer your question.

**Comment by Fbonazzi** [comment]
I had deleted my comment before you replied because I didn't realize your procedure is basically a key schedule. As such, it still has a place, but all other objections remain.

Also, please note that you (admittedly) do not know how AES works, so please refrain from asserting that your cipher is "much harder to break". AES not only has a key schedule, but it also has different modes of operation that change its overall behaviour quite a bit: this directly undermines your assertions that "AES uses last encrypted data to produce encrypted text" (depends on the mode) and that "AES has a static key and makes "rounds"" (you misunderstand the key schedule function).

**Comment by ikizir** [comment]
I was specifically talking about CBC mode Because people ask me questions like "AES is using the last encrypted byte too. What is the difference?"
