### ISSUE TITLE
Reimplement on Rust for even better security ? (no memory leaks) 

### ISSUE THREAD

**Issue by LifeIsStrange** [ikizir/HohhaDynamicXOR#5]
Also thanks for your really promising algorithm ! :)

**Comment by timtas** [comment]
Memory leaks in C can easily be avoided by proper coding. More seriously: subroutines aiming for maximum performance are generally implemented in C, as it's the fastest. And an encryption algorhythm certainly falls into that category. For complex application, another language might me a better choice.

**Comment by LifeIsStrange** [comment]
Yes but Rust allow a guarantee. 
As you wish !

**Comment by thagabe** [comment]
If he is looking forward to mainlining this to the kernel it has to be done in C

**Comment by LifeIsStrange** [comment]
Oh yeah ! I'm stupid ^^
Maybe one Day Linux code could support multiple langages instead of c11/assembly

**Comment by timtas** [comment]
May that day never come. You  can however already write user-space filesystems in different languages, I think that is sufficiently enough. Not really waiting for the memory management subsystem being rewritten in ruby or node.js

**Comment by LifeIsStrange** [comment]
But I don't understund why Linux kernel don't support others langages, it lose the avantages of others langages and also above all it lose many developpers :/

**Comment by timtas** [comment]
In kernel space, performance matters and the advantages of other languages are also often undesired. Nobody wants garbage collection in kernel space for instance. C just guarantees the best performance, at the cost of having everything to do yourself. But if you do everything yourself, you only do it when you really need it.

**Comment by LifeIsStrange** [comment]
But there is others features, like autogestion of the memory on Rust for avoid memory leaks, but yes you are probably right

**Comment by thagabe** [comment]
C is the lowest high-level language, as low as human readable language can get, thus it is the preferred language for the Kernel.

**Comment by ikizir** [comment]
I think, C is the best language for kernel development.
For crypto, even C is not enough sometimes, but, for more than 18 years I haven't written any lines of assembler. And I was never good enough to compete with optimization techniques of modern C compilers.
Download and make tests with the program guys.
I wrote a nice subroutine to encrypt a bmp file in order to visually see the encrypted patterns.
Try with a lot of different bmp files, and send to me if you see a pattern on the files.
And you are welcome LifeIsStrange :)

**Comment by LifeIsStrange** [comment]
Haha thanks ikizir !! But I know nothing in crypto and I don't know code :/ I'm a Just a teenager fan of free software !

**Comment by stylemistake** [comment]
Actually,
- Rust is as low-level as C, and one can easily translate source to machine code while writing a program. In other words, you have control over the machine code.
- Syntactic (FP) and compile-time (ownership system) abilities of Rust make it a superior language, because it results in a more concise, meaningful and **safe** code.

Of course that is impossible to submit into the kernel, but I see no reason to not to implement it in Rust.

**Comment by Happy-Ferret** [comment]
> May that day never come.

Unofficially (i e outside of mainline), it already has. 
There are multiple efforts of implementing kernel modules inside languages like [rust](https://github.com/tsgates/rust.ko) and [Haskell](https://wiki.haskell.org/Kernel_Modules).

Stable and secure is something else, of course.
